<?php

/**
 * BaseStackendCategoryContribution
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $StackendContributions
 * 
 * @method string                       getName()                  Returns the current record's "name" value
 * @method Doctrine_Collection          getStackendContributions() Returns the current record's "StackendContributions" collection
 * @method StackendCategoryContribution setName()                  Sets the current record's "name" value
 * @method StackendCategoryContribution setStackendContributions() Sets the current record's "StackendContributions" collection
 * 
 * @package    stackend
 * @subpackage model
 * @author     Thapelo Tsotetsi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStackendCategoryContribution extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stackend_category_contribution');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('StackendContribution as StackendContributions', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}