<?php

/**
 * BaseStackendAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $email
 * @property string $token
 * @property boolean $is_active
 * @property Doctrine_Collection $StackendCategories
 * @property Doctrine_Collection $StackendCategoryAffiliate
 * 
 * @method string              getUrl()                       Returns the current record's "url" value
 * @method string              getEmail()                     Returns the current record's "email" value
 * @method string              getToken()                     Returns the current record's "token" value
 * @method boolean             getIsActive()                  Returns the current record's "is_active" value
 * @method Doctrine_Collection getStackendCategories()        Returns the current record's "StackendCategories" collection
 * @method Doctrine_Collection getStackendCategoryAffiliate() Returns the current record's "StackendCategoryAffiliate" collection
 * @method StackendAffiliate   setUrl()                       Sets the current record's "url" value
 * @method StackendAffiliate   setEmail()                     Sets the current record's "email" value
 * @method StackendAffiliate   setToken()                     Sets the current record's "token" value
 * @method StackendAffiliate   setIsActive()                  Sets the current record's "is_active" value
 * @method StackendAffiliate   setStackendCategories()        Sets the current record's "StackendCategories" collection
 * @method StackendAffiliate   setStackendCategoryAffiliate() Sets the current record's "StackendCategoryAffiliate" collection
 * 
 * @package    stackend
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStackendAffiliate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stackend_affiliate');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('StackendCategory as StackendCategories', array(
             'refClass' => 'StackendCategoryAffiliate',
             'local' => 'affiliate_id',
             'foreign' => 'category_id'));

        $this->hasMany('StackendCategoryAffiliate', array(
             'local' => 'id',
             'foreign' => 'affiliate_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}