<?php

/**
 * BaseStackendCategoryAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $affiliate_id
 * @property StackendCategory $StackendCategory
 * @property StackendAffiliate $StackendAffiliate
 * 
 * @method integer                   getCategoryId()        Returns the current record's "category_id" value
 * @method integer                   getAffiliateId()       Returns the current record's "affiliate_id" value
 * @method StackendCategory          getStackendCategory()  Returns the current record's "StackendCategory" value
 * @method StackendAffiliate         getStackendAffiliate() Returns the current record's "StackendAffiliate" value
 * @method StackendCategoryAffiliate setCategoryId()        Sets the current record's "category_id" value
 * @method StackendCategoryAffiliate setAffiliateId()       Sets the current record's "affiliate_id" value
 * @method StackendCategoryAffiliate setStackendCategory()  Sets the current record's "StackendCategory" value
 * @method StackendCategoryAffiliate setStackendAffiliate() Sets the current record's "StackendAffiliate" value
 * 
 * @package    stackend
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStackendCategoryAffiliate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stackend_category_affiliate');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('affiliate_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('StackendCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('StackendAffiliate', array(
             'local' => 'affiliate_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}