stackend_category_contribution:
  class: sfDoctrineRouteCollection
  options:
    model:                StackendCategoryContribution
    module:               category_contribution
    prefix_path:          /category_contribution
    column:               id
    with_wildcard_routes: true

stackend_contribution:
  class: sfDoctrineRouteCollection
  options:
    model:                StackendContribution
    module:               contribution
    prefix_path:          /contribution
    column:               id
    with_wildcard_routes: true

stackend_affiliate:
  class: sfDoctrineRouteCollection
  options:
    model:                StackendAffiliate
    module:               affiliate
    prefix_path:          /affiliate
    column:               id
    with_wildcard_routes: true

stackend_category:
  class: sfDoctrineRouteCollection
  options:
    model:                StackendCategory
    module:               category
    prefix_path:          /category
    column:               id
    with_wildcard_routes: true

stackend_job:
  class: sfDoctrineRouteCollection
  options:
    model:                StackendJob
    module:               job
    prefix_path:          /job
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: job, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
