<?php

/**
 * BaseStackendCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $StackendJobs
 * @property Doctrine_Collection $StackendAffiliates
 * @property Doctrine_Collection $StackendCategoryAffiliate
 * 
 * @method string              getName()                      Returns the current record's "name" value
 * @method Doctrine_Collection getStackendJobs()              Returns the current record's "StackendJobs" collection
 * @method Doctrine_Collection getStackendAffiliates()        Returns the current record's "StackendAffiliates" collection
 * @method Doctrine_Collection getStackendCategoryAffiliate() Returns the current record's "StackendCategoryAffiliate" collection
 * @method StackendCategory    setName()                      Sets the current record's "name" value
 * @method StackendCategory    setStackendJobs()              Sets the current record's "StackendJobs" collection
 * @method StackendCategory    setStackendAffiliates()        Sets the current record's "StackendAffiliates" collection
 * @method StackendCategory    setStackendCategoryAffiliate() Sets the current record's "StackendCategoryAffiliate" collection
 * 
 * @package    stackend
 * @subpackage model
 * @author     Thapelo Tsotetsi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStackendCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stackend_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('StackendJob as StackendJobs', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('StackendAffiliate as StackendAffiliates', array(
             'refClass' => 'StackendCategoryAffiliate',
             'local' => 'category_id',
             'foreign' => 'affiliate_id'));

        $this->hasMany('StackendCategoryAffiliate', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'uniqueBy' => 
             array(
              0 => 'lang',
              1 => 'name',
             ),
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}