<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/01/24 10:22:08

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=stackend',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
