<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/02/09 07:41:42
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
