<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/02/09 07:41:43

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=127.0.0.1;dbname=stackend',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
