<?php

/**
 * StackendCategoryContributionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StackendCategoryContributionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StackendCategoryContributionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StackendCategoryContribution');
    }
    
    
    
  public function getActiveJobs()
  {
    $q = $this->createQuery('j')
      ->where('j.expires_at > ?', date('Y-m-d H:i:s', time()))
      ->orderBy('j.expires_at DESC');
 
    return $q->execute();
  }
  
  public function getWithJobs()
  {
    $q = $this->createQuery('c')
      ->leftJoin('c.StackendContributions j')
      ->where('j.expires_at > ?', date('Y-m-d H:i:s', time()));
 
    return $q->execute();
  }
}
