<?php

/**
 * StackendContribution
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    stackend
 * @subpackage model
 * @author     Thapelo Tsotetsi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StackendContribution extends BaseStackendContribution
{
	public function getCompanySlug()
	{
		return Stackend::slugify($this->getCompany());
	}
 
	public function getPositionSlug()
	{
		return Stackend::slugify($this->getPosition());
	}
 
	public function getLocationSlug()
	{
		return Stackend::slugify($this->getLocation());
	}
}
