<?php

/**
 * StackendContributionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StackendContributionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StackendContributionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StackendContribution');
    }
}