<?php

/**
 * StackendJob
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    stackend
 * @subpackage model
 * @author     Thapelo Tsotetsi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StackendJob extends BaseStackendJob
{
	public function getCompanySlug()
	{
		return Stackend::slugify($this->getCompany());
	}
 
	public function getPositionSlug()
	{
		return Stackend::slugify($this->getPosition());
	}
 
	public function getLocationSlug()
	{
		return Stackend::slugify($this->getLocation());
	}
	
	public function save(Doctrine_Connection $conn = null)
	{
		if ($this->isNew() && !$this->getExpiresAt())
		{
			$now = $this->getCreatedAt() ? $this->getDateTimeObject('created_at')->format('U') : time();
			$this->setExpiresAt(date('Y-m-d H:i:s', $now + 86400 * sfConfig::get('app_active_days')));
		}
		
		if (!$this->getToken())
		{
			$this->setToken(sha1($this->getEmail().rand(11111, 99999)));
		}		
 
		return parent::save($conn);
	}
	
	public function getTypeName()
	{
		$types = Doctrine_Core::getTable('StackendJob')->getTypes();
		return $this->getType() ? $types[$this->getType()] : '';
	}
 
	public function isExpired()
	{
		return $this->getDaysBeforeExpires() < 0;
	}
 
	public function expiresSoon()
	{
		return $this->getDaysBeforeExpires() < 5;
	}
 
	public function getDaysBeforeExpires()
	{
		return ceil(($this->getDateTimeObject('expires_at')->format('U') - time()) / 86400);
	}
	
	public function publish()
	{
		$this->setIsActivated(true);
		$this->save();
	}
}
