<?php

/**
 * StackendContributionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StackendContributionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StackendContributionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StackendContribution');
    }
    
	public function getActiveJobs(Doctrine_Query $q = null)
	{
	  if (is_null($q))
	  {
		$q = Doctrine_Query::create()
		  ->from('StackendContribution j');
	  }
	 
	  $q->andWhere('j.expires_at > ?', date('Y-m-d H:i:s', time()))
		->addOrderBy('j.expires_at DESC');
	 
	  return $q->execute();
	}
  
  public function getWithJobs()
  {
    $q = $this->createQuery('c')
      ->leftJoin('c.JobeetJobs j')
      ->where('j.expires_at > ?', date('Y-m-d H:i:s', time()));
 
    return $q->execute();
  }
  
	public function retrieveActiveContribution(Doctrine_Query $q)
	{
		return $this->addActiveJobsQuery($q)->fetchOne();
	}
	
	public function addActiveJobsQuery(Doctrine_Query $q = null)
	{
		if (is_null($q))
		{
			$q = Doctrine_Query::create()
				->from('StackendContribution j');
		}
 
		$alias = $q->getRootAlias();
 
		$q->andWhere($alias . '.expires_at > ?', date('Y-m-d H:i:s', time()))
			->addOrderBy($alias . '.created_at DESC');
			
		$q->andWhere($alias . '.is_activated = ?', 1);
 
		return $q;
   }
  
}
