# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

category:
  url:     /category/:slug.:sf_format
  class:   sfDoctrineRoute
  param:   { module: category, action: show, sf_format: html }
  options: { model: StackendCategory, type: object }
  requirements:
    sf_format: (?:html|atom)

job:
  class:   sfDoctrineRouteCollection
  options:
    model:          StackendJob
    column:         token
    object_actions: { publish: put }
  requirements:
    token: \w+
 
job_show_user:
  url:     /job/:company_slug/:location_slug/:id/:position_slug
  class:   sfDoctrineRoute
  options:
    model: StackendJob
    type:  object
    method_for_query: retrieveActiveJob
  param:   { module: job, action: show }
  requirements:
    id: \d+
    sf_method: [GET]

contribution:
  class:   sfDoctrineRouteCollection
  options:
    model:          StackendContribution
    column:         token
    object_actions: { publish: put }
  requirements:
    token: \w+

contribution_show_user:
  url:     /contribution/:company_slug/:location_slug/:id/:position_slug
  class:   sfDoctrineRoute
  options:
    model: StackendContribution
    type:  object
    method_for_query: retrieveActiveContribution
  param:   { module: contribution, action: show }
  requirements:
    id: \d+
    sf_method: [GET]

job_search:
  url:   /search
  param: { module: job, action: search }
    
api_jobs:
  url:     /api/:token/jobs.:sf_format
  class:   sfDoctrineRoute
  param:   { module: api, action: list }
  options: { model: StackendJob, type: list, method: getForToken }
  requirements:
    sf_format: (?:xml|json|yaml)
    
affiliate:
  class:   sfDoctrineRouteCollection
  options:
    model: StackendAffiliate
    actions: [new, create]
    object_actions: { wait: get }
 
# default rules
homepage:
  url:   /
  param: { module: job, action: index }
 
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
