<?php

/**
 * StackendCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StackendCategoryTable extends PluginStackendCategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object StackendCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StackendCategory');
    }
}