<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/01/31 19:47:10
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
