<?php

/**
 * StackendContributionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginStackendContributionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StackendContributionTable
     */

      static public $types = array(
      'full-time' => 'Full time',
      'part-time' => 'Part time',
      'freelance' => 'Freelance',
       );
 
    public function getTypes()
    {
      return self::$types;
    }


    public static function getInstance()
    {
        return Doctrine_Core::getTable('StackendContribution');
    }
 
  public function retrieveActiveContribution(Doctrine_Query $q)
  {
    return $this->addActiveJobsQuery($q)->fetchOne();
  }
 
  public function getActiveJobs(Doctrine_Query $q = null)
  {
    return $this->addActiveJobsQuery($q)->execute();
  }
 
  public function countActiveJobs(Doctrine_Query $q = null)
  {
    return $this->addActiveJobsQuery($q)->count();
  }
 
  public function addActiveJobsQuery(Doctrine_Query $q = null)
  {
    if (is_null($q))
    {
      $q = Doctrine_Query::create()
        ->from('StackendContribution j');
    }
 
    $alias = $q->getRootAlias();
 
    $q->andWhere($alias . '.expires_at > ?', date('Y-m-d H:i:s', time()))
      ->addOrderBy($alias . '.created_at DESC');
 
  $q->andWhere($alias . '.is_activated = ?', 1);
 
  return $q;
  } 
    
  public function retrieveBackendContributionList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
 
    $q->leftJoin($rootAlias . '.StackendCategoryContribution c');
 
    return $q;
  }

}
