<?php

/**
 * StackendCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginStackendCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StackendCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StackendCategory');
    }
    
    public function getWithJobs()
	{
		$q = $this->createQuery('c')
			->leftJoin('c.StackendJobs j')
			->where('j.expires_at > ?', date('Y-m-d H:i:s', time()));
		
		$q->andWhere('j.is_activated = ?', 1);
 
		return $q->execute();
	}
}
