all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=127.0.0.1;dbname=stackend'
      username: root
      password: 
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=127.0.0.1;dbname=stackend_test'
      username: root
      password:
production:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=5.9.129.186;dbname=stackend'
      username: thapelo
      password: 407thapelo
