StackendCategoryContribution:
  actAs: { Timestampable:~, Sluggable:fields: [name] }
   
  columns:
    name: { type: string(255), notnull: true, unique: true }
 
StackendContribution:
  actAs: { Timestampable: ~ }
  columns:
    category_id:  { type: integer, notnull: true }
    type:         { type: string(255) }
    company:      { type: string(255), notnull: true }
    logo:         { type: string(255) }
    url:          { type: string(255) }
    position:     { type: string(255), notnull: true }
    location:     { type: string(255), notnull: true }
    description:  { type: string(4000), notnull: true }
    how_to_apply: { type: string(4000), notnull: true }
    token:        { type: string(255), notnull: true, unique: true }
    is_public:    { type: boolean, notnull: true, default: 1 }
    is_activated: { type: boolean, notnull: true, default: 0 }
    email:        { type: string(255), notnull: true }
    expires_at:   { type: timestamp, notnull: true }
  relations:
    StackendCategoryContribution: { onDelete: CASCADE, local: category_id, foreign: id, foreignAlias: StackendContributions } 
